services:
  db:
    image: postgres:16
    container_name: tandela-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tandela
    ports:
      - "5432:5432"
    volumes:
      - tandela_data:/var/lib/postgresql/data

volumes:
  tandela_data:
